// spotify actions.
export const GET_USER_SPOTIFY_PROFILE = "GET_USER_SPOTIFY_PROFILE";
export const GET_USER_SPOTIFY_PLAYLISTS = "GET_USER_SPOTIFY_PLAYLISTS";
export const POST_USER_SPOTIFY_PLAYLIST = "POST_USER_SPOTIFY_PLAYLIST";

// tumblr actions.
export const GET_USER_TUMBLR_POSTS = "GET_USER_TUMBLR_POSTS";
