// spotify actions.
export const GET_USER_SPOTIFY_PROFILE = 'GET_USER_SPOTIFY_PROFILE';
export const GET_USER_SPOTIFY_PROFILE_CLEAR = 'GET_USER_SPOTIFY_PROFILE_CLEAR';
export const GET_USER_SPOTIFY_PROFILE_ERROR = 'GET_USER_SPOTIFY_PROFILE_ERROR';
export const GET_USER_SPOTIFY_PROFILE_ERROR_CLEAR =
  'GET_USER_SPOTIFY_PROFILE_ERROR_CLEAR';

export const POST_USER_SPOTIFY_PLAYLIST = 'POST_USER_SPOTIFY_PLAYLIST';
export const POST_USER_SPOTIFY_PLAYLIST_CLEAR =
  'POST_USER_SPOTIFY_PLAYLIST_CLEAR';
export const POST_USER_SPOTIFY_PLAYLIST_ERROR =
  'POST_USER_SPOTIFY_PLAYLIST_ERROR';
export const POST_USER_SPOTIFY_PLAYLIST_ERROR_CLEAR =
  'POST_USER_SPOTIFY_PLAYLIST_ERROR_CLEAR';

// tumblr actions.
export const GET_USER_TUMBLR_POSTS = 'GET_USER_TUMBLR_POSTS';
export const GET_USER_TUMBLR_POSTS_CLEAR = 'GET_USER_TUMBLR_POSTS_CLEAR';
export const GET_USER_TUMBLR_POSTS_ERROR = 'GET_USER_TUMBLR_POSTS_ERROR';
export const GET_USER_TUMBLR_POSTS_ERROR_CLEAR =
  'GET_USER_TUMBLR_POSTS_ERROR_CLEAR';

// TODO: maybe we do not need so many actions, check it.

export const GET_POPULAR_BLOGS = 'GET_POPULAR_BLOGS';

export const REQUEST_ACTIVE = 'REQUEST_ACTIVE';