import React, { Component } from 'react';
import connect from 'react-redux/es/connect/connect';

import './success.css';
import { bindActionCreators } from 'redux';
import { clearPostsAndErrors } from '../../actions/tumblr';

class Success extends Component {
  constructor(props) {
    super(props);

    this.handleGenerateAnotherPlaylist = this.handleGenerateAnotherPlaylist.bind(this);
    this.openPlaylist = this.openPlaylist.bind(this);
  }

  handleGenerateAnotherPlaylist() {
    this.props.clearPostsAndErrors();
  }

  openPlaylist() {
    window.open(`${ this.props.spotify.playlist.data.external_urls.spotify }`, '_blank');
  }

  render() {
    let { playlist } = this.props.spotify;
    let { profile } = this.props.tumblr;

    let twitterHref = '';
    let tumblrHref = '';

    if ( playlist.data ) {
      const twitterText = `a playlist of ${ profile.name }.tumblr.com, generated by genly.com`;
      twitterHref = `http://twitter.com/share?text=${ twitterText }&url=${ playlist.data.external_urls.spotify }&hashtags=genly,spotify,playlist`;

      const playlistHref = `https://open.spotify.com/user/${ this.props.spotify.profile.id }/playlist/${ playlist.data.id }`;
      tumblrHref = `https://www.tumblr.com/widgets/share/tool?shareSource=legacy&canonicalUrl=${ playlistHref }&posttype=audio`;
    }

    return (
      <div>
        { playlist['data'] && playlist['data']['snapshot_id'] ? (
          <div className="col-md-6 centered text-center">
            <h4><span>Your playlist has been generated.</span></h4>
            <div className="success-buttons">
              <button
                onClick={ this.handleGenerateAnotherPlaylist }
                className="process-button offset"
              >
                generate
                another
              </button>
              <button
                onClick={ this.openPlaylist }
                className="process-button offset "
              >
                open playlist
              </button>
            </div>
            <div className="social">
              <ul>
                <li>
                  <a
                    title="github"
                    href={ twitterHref }
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <i className="fab fa-twitter"></i>
                  </a>
                </li>
                <li>
                  <a
                    title="github"
                    href={ tumblrHref }
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <i className="fab fa-tumblr"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        ) : null }
      </div>
    );
  }
}

function mapStateToProps(state) {
  return {
    spotify: state.spotify,
    tumblr: state.tumblr
  };
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators({ clearPostsAndErrors }, dispatch);
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Success);
