import React, { Component } from "react";
import { bindActionCreators } from "redux";
import connect from "react-redux/es/connect/connect";

// actions.
import { clearPostsAndErrors } from "../../actions/tumblr";
import { postUserPlaylist } from "../../actions/spotify";

// css.
import "./playlist.css";

// components.
import Track from "../track/track";
import Information from "../information/information";
import Success from "../success/success";
import Footer from "../footer/footer";
import Pagination from "../pagination/pagination";

let audio = new Audio();

class Playlist extends Component {
  constructor(props) {
    super(props);

    this.state = {
      currentPage: 1,
      tracksPerPage: 8,
      playing: false,
      currentTrackId: null
    };

    this.handlePagination = this.handlePagination.bind(this);
    this.nextPage = this.nextPage.bind(this);
    this.previousPage = this.previousPage.bind(this);
    this.playAudio = this.playAudio.bind(this);
    this.stopAudio = this.stopAudio.bind(this);
    this.handleGeneratePlaylist = this.handleGeneratePlaylist.bind(this);
    this.handleGenerateAnotherPlaylist = this.handleGenerateAnotherPlaylist.bind(
      this
    );
  }

  playAudio(previewUrl, trackId) {
    audio.src = previewUrl;

    this.setState({
      playing: true,
      currentTrackId: trackId
    });

    audio.play();
  }

  stopAudio() {
    this.setState({
      playing: false,
      currentTrackId: null
    });

    audio.pause();
  }

  handlePagination(event) {
    this.setState({
      currentPage: Number(event.target.id)
    });
  }

  nextPage() {
    this.setState({
      currentPage: this.state.currentPage + 1
    });
  }

  previousPage() {
    this.setState({
      currentPage: this.state.currentPage - 1
    });
  }

  handleGeneratePlaylist() {
    this.props.postUserPlaylist(
      this.props.tumblr.profile.name + " | genly",
      "generated by genly.",
      false,
      this.props.tumblr.tracks
    );
  }

  handleGenerateAnotherPlaylist() {
    this.props.clearPostsAndErrors();
  }

  render() {
    let { tracks, profile } = this.props.tumblr;
    let { playlist } = this.props.spotify;
    let { currentPage, tracksPerPage, playing, currentTrackId } = this.state;

    const indexOfLastTrack = currentPage * tracksPerPage;
    const indexOfFirstTrack = indexOfLastTrack - tracksPerPage;
    const currentTracks = tracks.slice(indexOfFirstTrack, indexOfLastTrack);

    const renderTracks = currentTracks.map(track => {
      return (
        <div className="col-md-3 col-6" key={track.id}>
          <Track
            stopAudio={this.stopAudio}
            playAudio={this.playAudio}
            currentTrackId={currentTrackId}
            playing={playing}
            track={track}
          />
        </div>
      );
    });

    const countOfPage = Math.ceil(tracks.length / tracksPerPage);
    const pageNumbers = [];

    for (let i = 1; i <= countOfPage; i++) {
      pageNumbers.push(i);
    }

    const renderPageNumbers = pageNumbers.map(number => {
      return (
        <Pagination
          number={number}
          currentPage={currentPage}
          handlePagination={this.handlePagination}
        />
      );
    });

    return (
      <div>
        {tracks.length > 0 && !playlist["snapshot_id"] ? (
          <div className="container">
            <div className="row buttons">
              <div className="col-md-6 ">
                <Information
                  blogProfile={profile}
                  countOfTracks={tracks.length}
                />
              </div>

              <div className="col-md-6 save-playlist text-center">
                <div>
                  <div
                    className="float-left col-md-5 generate-button"
                    onClick={this.handleGenerateAnotherPlaylist}
                  >
                    generate another
                    <div />
                    <i className="fa fa-times" />
                  </div>
                  <div
                    className="float-right col-md-5 save-button"
                    onClick={this.handleGeneratePlaylist}
                  >
                    save playlist
                    <div />
                    <i className="fa fa-check" />
                  </div>
                </div>
              </div>
            </div>

            <div className="row">
              {renderTracks}
            </div>

            <div className="center">
              <div className="pagination">
                <a onClick={currentPage <= 1 ? null : this.previousPage}>
                  <i className="fas fa-angle-left" />
                </a>
                {renderPageNumbers}
                <a onClick={currentPage >= countOfPage ? null : this.nextPage}>
                  <i className="fas fa-angle-right" />
                </a>
              </div>
            </div>
          </div>
        ) : null}
        <Success />

        {tracks.length > 0 && !playlist["snapshot_id"] ? (<Footer isFixed={false} />) : <Footer isFixed={true} />}
      </div>
    );
  }
}

function mapStateToProps(state) {
  console.log(state);
  return {
    tumblr: state.tumblr,
    spotify: state.spotify
  };
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators(
    { clearPostsAndErrors, postUserPlaylist },
    dispatch
  );
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Playlist);
